spring:
  application.name: gi-sink
  output.ansi.enabled: always
  jpa.hibernate.ddl-auto: none
  datasource:
    url: jdbc:h2:file:./target/h2db/gi;DB_CLOSE_ON_EXIT=FALSE
    username: gi
    password:

  jackson:
    serialization:
      write-date-timestamps-as-nanoseconds: false
    deserialization:
      read-date-timestamps-as-nanoseconds: false

  cloud.stream:
    bindings.input:
#      destination: greetings
      destination: transformed-greetings
      content-type: application/json

server:
  port: -1
management:
  port: 8999
  context-path: /manage

security:
  basic.path: ${management.context-path}/**
  user: # Override credentials in production.
    name: admin
    password: secret

logging.level:
  net.robi42.gisink: DEBUG
